- hosts: localhost
  tasks:
  - name: Set the  hostname to {{hostname}}
    shell: "hostnamectl hostname {{hostname}}.local.net"
    ignore_errors: yes

  - name: Configure Fastest mirror for DNF
    lineinfile:
        path: /etc/dnf/dnf.conf
        line: "fastestmirror=1"
        backup: "true"

  - name: Configure Maximum parallel downloads for DNF
    lineinfile:
        path: /etc/dnf/dnf.conf
        line: "max_parallel_downloads=10"
        backup: "true"

  - name: Configure usage of delta rpms for DNF
    lineinfile:
        path: /etc/dnf/dnf.conf
        line: "deltarpm=true"
        backup: "true"

  - name: Enable Fusion rpm repository (free)
    shell: "dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y"
    ignore_errors: yes

  - name: Enable Fusion rpm  repository (non-free)
    shell: "dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y"
    ignore_errors: yes

  - name: check and  update all  the upgradeble packages in the  system
    dnf:
           name: "*"
           state: latest
    ignore_errors: yes

  - name: Install Multi Media codecs
    script: /home/jherrera/Ansible/post-installation/scripts/Multimedia.sh
    ignore_errors: yes

  - name: Add the flathub flatpak repository remote to the installation
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Install multiple Flatpak packages
    community.general.flatpak:
      name: "{{ item }}"
      state: present
    loop:
          - com.bitwarden.desktop
          - com.sindresorhus.Caprine
          - com.spotify.Client
          - io.github.mimbrero.WhatsAppDesktop
          - com.brave.Browser
          - com.visualstudio.code
          - com.google.Chrome
        # - org.libreoffice.LibreOffice
          - com.sindresorhus.Caprine
          - io.github.pwr_solaar.solaar

  - name: Install Multi Media Software
    dnf:
            name: "{{ item }}"
            state: present
    ignore_errors: yes
    loop:
            - gstreamer-plugins-bad
#            - gstreamer-plugins-bad-free-extras
            - gstreamer-plugins-bad-nonfree
            - gstreamer-plugins-ugly
            - gstreamer-ffmpeg
            - gstreamer1-libav
            - gstreamer1-plugins-bad-free-extras
            - gstreamer1-plugins-bad-freeworld
            - gstreamer1-plugins-base-tools
            - gstreamer1-plugins-good-extras
            - gstreamer1-plugins-ugly
            - gstreamer1-plugins-bad-free
            - gstreamer1-plugins-good
            - gstreamer1-plugins-base
            - gstreamer1
            - audacious.x86_64
            - audacity-freeworld
            - vlc
            - audacious-plugins-freeworld.x86_64
            - alsa-plugins-pulseaudio
            - youtube-dl

  - name: Install Software
    dnf:
            name: "{{ item }}"
            state: present
    ignore_errors: yes
    loop:
            - filezilla
            - ktorrent
            - gimp
            - gimp-data-extras
            # - thunderbird
            - google-droid-*
            - skanlite
            - kfind
            - krita
            - digikam
            - kcolorchooser
            - inkscape

  # - name: Install  Printer Software
  #   dnf:
  #           name: "{{ item }}"
  #           state: present
  #   ignore_errors: yes
  #   loop:
  #           - hplip-gui
  #           - cups-pdf
  #           - hplip-common

  - name: Install system tools
    dnf:
            name: "{{ item }}"
            state: present
    ignore_errors: yes
    loop:
            - htop
            - libcurl
            - vim
            - liveusb-creator
            - gnome-tweak-tool
            - dconf-editor
            - nmap
            - inxi.noarch
            - glances
            - neofetch
            - screenfetch
            - hunspell-nl
            - grub-customizer
            - tldr
            - btop
            - powertop
            - neovim
            - tlp
            - flatseal
            - zsh
            - python3-ansible-lint
            - cabextract
            - lzip
            - p7zip
            - p7zip-plugins
            - unrar
            - firewall-config
            - pcsc-lite.x86_64
            - pcsc-tools.x86_64
            - pcsc-lite-ccid.x86_64
            - fd-find
            - kate
            - wavemon
            - f2f

  - name: Install Development libraries and  Tools
    dnf:
               name: "{{ item }}"
               state: present
    ignore_errors: yes
    loop:
               - kernel-devel
               - dkms
               - kernel-headers
               - make
               - gcc
               - gcc-c++
               - icedtea-web
               - java-openjdk


  - name: Install msttcorefonts
    script: /home/jherrera/Ansible/post-installation/scripts/msttcorefonts.sh
    ignore_errors: yes

  - name: Install ioscheduler 
    script: /home/jherrera/Ansible/post-installation/scripts/ioscheduler.sh
    ignore_errors: yes

    ## finetuning desktop system:

  - name: Creates Themes directory in the  homedir
    ansible.builtin.file:
      path: "$HOME/.themes"
      state: directory

  - name: Creates icons directory in the  homedir
    ansible.builtin.file:
      path: "$HOME/.icons"
      state: directory

  - name: Add repository for  Virtualbox 7
    ansible.builtin.yum_repository:
      name: virtualbox
      description: Virtualbox 7 Repo
      baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
      enabled: yes

  - name: Import gpg key for Virtualbox
    ansible.builtin.shell:
      cmd: "rpm --import https://www.virtualbox.org/download/oracle_vbox.asc"

  - name: Install the latest version of Virtualbox 7
    ansible.builtin.dnf:
      name: VirtualBox-7.0
      state: latest

  - name: Add {{ user }} to vboxusers group
    ansible.builtin.user:
      name: "{{ user }}"
      groups: vboxusers
      append: yes




# Todo:
# ksave
