- hosts: localhost
  tasks:
          #  - name: Install gimp
          #    snap:
          #            name: gimp
  - name: Install Graphical Software
    package:
            name: "{{ item }}"
            state: present
    loop:
            - digikam
            - inkscape
  - name: Install Multi Media Software
    package:
            name: "{{ item }}"
            state: present
    loop:
            - audacious
            - audacity
            - vlc
            - youtube-dl
            - clementine
            - ubuntu-restricted-extras
            - ffmpeg 
            - winff 
            - mencoder
            - libdvdread4 
            - icedax 
            - easytag 
            - id3tool 
            - lame 
            - libmad0 
            - mpg321
            - libavcodec-extra 
            - flac 
            - faac 
            - faad 
            - libdvd-pkg 
            - libaacs0 
            - libbluray-bdj 
            - freeglut3-dev 
            - mesa-common-dev
            - ffmpeg2theora 
            - libmpeg2-4 
            - mpeg3-utils 
            - mpegdemux 
            - liba52-dev 
            - mpeg2dec 
            - vorbis-tools 
            - id3v2 
            - mpg123 
            - libflac++6v5:i386 
            - libflac++6v5 
            - libjpeg-progs
            - libdvdcss2 
            - libdvdnav4 
            - openshot-qt 


  - name: Install system tools 
    package:
            name: "{{ item }}"
            state: present
    loop:
            - htop
            - vim  
            - nmap
            - inxi  
            - glances
            - neofetch
            - screenfetch
            - speedcrunch
  - name: Install Archive Software
    package:
               name: "{{ item }}"
               state: present
    loop: 
               - cabextract 
               - lzip
               - p7zip
               - p7zip-rar
  - name: Install Development libraries and  Tools
    package:
               name: "{{ item }}"
               state: present
    loop:
               - build-essential
               - cmake
               - automake
               - autoconf
               - libc6-i386 
               - libncurses5:i386 
               - libstdc++6:i386 
               - lib32z1 
               - libc6:i386 
               - libbz2-1.0:i386
               - libqtwebkit4
               - dkms
               - make
               - gcc
  - name: Install Printer Software
    package:
               name: "{{ item }}"
               state: present
    loop:
               - hplip
               - hplip-gui
               -  printer-driver-cups-pdf
               
