- hosts: localhost
  tasks:
  - name: Install Graphical Software
    package:
            name: "{{ item }}"
            state: present
    loop:
            - digikam
            - kcolorchooser
            - inkscape
            - gimp

  - name: Install Multi Media Software
    package:
            name: "{{ item }}"
            state: present
    loop:
            - audacious
            - audacity
            - vlc
            - youtube-dl
            - clementine
            - kubuntu-restricted-extras
            - ffmpeg 
            - winff 
            - mencoder
            - icedax 
            - easytag 
            - id3tool 
            - lame 
            - libmad0 
            - mpg321
            - libavcodec-extra 
            - flac 
            - faac 
            - faad 
            - libdvd-pkg 
            - libaacs0 
            - libbluray-bdj 
            - freeglut3-dev 
            - mesa-common-dev
            - ffmpeg2theora 
            - libmpeg2-4 
            - mpeg3-utils 
            - mpegdemux 
            - liba52-dev 
            - mpeg2dec 
            - vorbis-tools 
            - id3v2 
            - mpg123 
            - libflac++6v5 
            - libjpeg-progs
            - libdvdcss2 
            - libdvdnav4 
            - kdenlive 
            - openshot-qt 
            - amarok
            - catimg
            - cmus
            - krita


  - name: Install system tools 
    package:
            name: "{{ item }}"
            state: present
    loop:
            - htop
            - vim  
            - nmap
            - inxi  
            - glances
            - neofetch
            - screenfetch
            - gufw
            - ktorrent
            - yakuake
            - speedcrunch
            - kfind
            - kio-gdrive
            - glances
            - zsh
            - fd-find
            - kup-backup
            - ranger
            - ripgrep
            - skanlite
            - ttf-mscorefonts-installer

  - name: Install Archive Software
    package:
               name: "{{ item }}"
               state: present
    loop: 
               - cabextract 
               - lzip
               - p7zip
               - p7zip-rar
  - name: Install Development libraries and  Tools
    package:
               name: "{{ item }}"
               state: present
    loop:
               - build-essential
               - cmake
               - automake
               - autoconf
               - libc6-i386 
               - lib32z1 
               - dkms
               - make
               - gcc
  - name: Install multiple Flatpak packages
    community.general.flatpak:
      name: "{{ item }}"
      state: present
    loop:
        - com.bitwarden.desktop
        - com.sindresorhus.Caprine
        - com.spotify.Client
        - io.github.mimbrero.WhatsAppDesktop
        - com.brave.Browser
        - com.visualstudio.code
        - com.google.Chrome
        - org.libreoffice.LibreOffice
        - com.sindresorhus.Caprine
