  - name: Configure Fastest mirror for DNF
    lineinfile:
        path: /etc/dnf/dnf.conf
        line: "fastestmirror=1"
        backup: "true"

  - name: Configure Maximum parallel downloads for DNF
    lineinfile:
        path: /etc/dnf/dnf.conf
        line: "max_parallel_downloads=10"
        backup: "true"

  - name: Configure usage of delta rpms for DNF
    lineinfile:
        path: /etc/dnf/dnf.conf
        line: "deltarpm=true"
        backup: "true"

  - name: Enable Fusion rpm repository (free)
    shell: "dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y"

  - name: Enable Fusion rpm  repository (non-free)
    shell: "dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y"

  - name: check and  update all  the upgradeble packages in the  system
    dnf:
           name: "*"
           state: latest

  - name: Add the flathub flatpak repository remote to the installation
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: configure  wayland to use  different resolutions 
    script: /home/jherrera/Ansible/post-installation/scripts/wayland_config.sh
    ignore_errors: yes 

  ## finetuning desktop system:

  - name: Creates Themes directory in the  homedir
    ansible.builtin.file:
      path: "$HOME/.themes"
      state: directory

  - name: Creates icons directory in the  homedir
    ansible.builtin.file:
      path: "$HOME/.icons"
      state: directory
      
  - name: Configure Wayland on gnome
    shell: "gsettings set org.gnome.mutter experimental-features \"['scale-monitor-framebuffer']\""
    ignore_errors: yes
  
  - name:  enable the  GTK themes for the  flatpak software
    shell: "sudo flatpak override --filesystem=$HOME/.theme"
    ignore_errors: yes

  - name:  enable the  GTK icons for the  flatpak software
    shell: "sudo flatpak override --filesystem=$HOME/.icons"
    ignore_errors: yes
  
  # - name:  Disable SELinux
  #   ansible.builtin.replace:
  #     path: /etc/selinux/config
  #     regexp: 'SELINUX=enforcing'
  #     replace: 'SELINUX=disabled'
  #   ignore_errors: yes

  - name:  Increase console font
    ansible.builtin.replace:
      path: /etc/vconsole.conf
      regexp: 'FONT="eurlatgr"'
      replace: 'FONT="ter-132n"'
    ignore_errors: yes