  - name: Configure Fastest mirror for DNF
    lineinfile:
        path: /etc/dnf/dnf.conf
        line: "fastestmirror=1"
        backup: "true"

  - name: Configure Maximum parallel downloads for DNF
    lineinfile:
        path: /etc/dnf/dnf.conf
        line: "max_parallel_downloads=10"
        backup: "true"

  - name: Configure usage of delta rpms for DNF
    lineinfile:
        path: /etc/dnf/dnf.conf
        line: "deltarpm=true"
        backup: "true"

  - name: Enable Fusion rpm repository (free)
    shell: "dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -y"

  - name: Enable Fusion rpm  repository (non-free)
    shell: "dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y"

  - name: check and  update all  the upgradeble packages in the  system
    dnf:
           name: "*"
           state: latest

  - name: Add the flathub flatpak repository remote to the installation
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    
  # - name:  Disable SELinux
  #   ansible.builtin.replace:
  #     path: /etc/selinux/config
  #     regexp: 'SELINUX=enforcing'
  #     replace: 'SELINUX=disabled'
  #   ignore_errors: yes

  - name:  Increase console font
    ansible.builtin.replace:
      path: /etc/vconsole.conf
      regexp: 'FONT="eurlatgr"'
      replace: 'FONT="ter-132n"'
    ignore_errors: yes

  ## base  software installation
  - name: Install base software packages
    dnf:
          name: "{{ item }}"
          state: present
    ignore_errors: yes
    loop: 
         - htop
         - libcurl
         - vim  
         - liveusb-creator
         - nmap
         - inxi.noarch  
         - glances
         - screenfetch
         - fastfetch
         - hunspell-nl
         - tldr
         - btop
         - powertop
         - neovim
         - flatseal
         - python3-ansible-lint
#        - timeshift
         - btrfs-assistant
         - terminus-fonts-console
         - wavemon
         - fzf
         - bleachbit
         - clamtk
         - cmatrix
         - dnfdragora
         
  - name: Install smartcard Software
    dnf:
           name: "{{ item }}"
           state: present
    ignore_errors: yes
    loop: 
         - pcsc-lite.x86_64
         - pcsc-tools.x86_64
         - pcsc-lite-ccid.x86_64

  - name: Install Archive Software
    dnf:
          name: "{{ item }}"
          state: present
    ignore_errors: yes
    loop: 
         - cabextract 
         - lzip
         - p7zip
         - p7zip-plugins
         - unrar  

  - name: Install Development libraries and  Tools
    dnf:
         name: "{{ item }}"
         state: present
    ignore_errors: yes
    loop:
         - kernel-devel
         - dkms
         - kernel-headers
         - make
         - gcc
         - gcc-c++
         - java-openjdk

 ## install tgpt 
  - name: Download tgpt binary
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/a9n0n/tgpt/main/install.sh"
      dest: "/tmp/tgpt_install.sh"
      mode: '0755'

  - name: Execute installation script
    ansible.builtin.shell: curl -sSL https://raw.githubusercontent.com/a9n0n/tgpt/main/install.sh | bash -s -- /usr/local/bin
    args:
      creates: "{{ install_path }}"

  - name: Verify tgpt installation
    ansible.builtin.command: tgpt --version
    register: tgpt_check
    changed_when: false

  - name: Print version
    ansible.builtin.debug:
      msg: "Successfully installed: {{ tgpt_check.stdout }}"