---
    # === Group updates ===
    - name: Update core, multimedia, and sound-and-video groups
      ansible.builtin.dnf:
        name:
          - "@core"
          - "@multimedia"
          - "@sound-and-video"
        state: latest
        install_weak_deps: no
        exclude: PackageKit-gstreamer-plugin
        allowerasing: yes

    # === Swap ffmpeg-free -> ffmpeg ===
    - name: Swap ffmpeg-free with ffmpeg
      ansible.builtin.dnf:
        name: ffmpeg
        state: present
        allowerasing: yes
        allow_downgrade: yes
        disable_excludes: all
      notify:
        - remove ffmpeg-free

    # === Install GStreamer plugins and ffmpeg ===
    - name: Install GStreamer plugins and ffmpeg
      ansible.builtin.dnf:
        name:
          - "gstreamer1-plugins-bad-*"
          - "gstreamer1-plugins-good-*"
          - "gstreamer1-plugins-base"
          - "gstreamer1-plugin-openh264"
          - "gstreamer1-libav"
          - "ffmpeg"
          - "gstreamer-ffmpeg"
        exclude: gstreamer1-plugins-bad-free-devel
        state: present

    # === Install lame ===
    - name: Install lame codecs (excluding lame-devel)
      ansible.builtin.dnf:
        name: "lame*"
        exclude: lame-devel
        state: present

    # === Upgrade Multimedia group with optional packages ===
    - name: Upgrade Multimedia group with optional packages
      ansible.builtin.dnf:
        name: "@Multimedia"
        state: latest
        with_optional: yes

    # === Intel Media Driver ===
    - name: Install Intel media driver
      ansible.builtin.dnf:
        name: intel-media-driver
        state: present

    # === Enabbling OopenH264 Codec... ===
    - name: "Enabling OpenH264 codec..." 
      shell: "dnf config-manager setopt fedora-cisco-openh264.enabled=1"
      ignore_errors: yes

    # === Extra Multimedia Software ===
    - name: Install Extra Multimedia Software
      dnf:
          name: "{{ item }}"
          state: present
      ignore_errors: yes
      loop:
          - youtube-dl
          - audacious.x86_64
          - audacity-freeworld
          - vlc
          - audacious-plugins-freeworld.x86_64
          - alsa-plugins-pulseaudio


  handlers:
    - name: remove ffmpeg-free
      ansible.builtin.dnf:
        name: ffmpeg-free
        state: absent
        allowerasing: yes
