
# Flatpak Software Installation 
  - name: Install multiple Flatpak packages
    community.general.flatpak:
      name:
       - app.drey.EarTag
       - app.zen_browser.zen
       
       - com.beavernotes.beavernotes
       - com.belmoussaoui.Obfuscate
       - com.bitwarden.desktop
       - com.emqx.MQTTX
       - com.felipekinoshita.Wildcard
       - com.github.ADBeveridge.Raider
       - com.github.unrud.VideoDownloader
       - com.jgraph.drawio.desktop
       - com.rtosta.zapzap
       - com.spotify.Client
       - com.surfshark.Surfshark
       - dev.bragefuglseth.Fretboard 
       - dev.fredol.open-tv
       - io.github.Omniaevo.mqtt5-explorer
       - io.github.alainm23.planify
       - io.github.flattool.Warehouse
       - io.github.giantpinkrobots.varia
       - io.github.janbar.noson
       - io.github.qwersyk.Newelle
       - io.github.wartybix.Constrict
       - io.gitlab.adhami3310.Converter
       - io.gitlab.adhami3310.Impression
       - io.gitlab.librewolf-community
       - io.gpt4all.gpt4all.Locale
       - md.obsidian.Obsidian 
       - net.code_industry.MasterPDFEditor 
       - org.angryip.ipscan
       - net.nokyan.Resources
       - io.gitlab.theevilskeleton.Upscaler
       - io.github.amit9838.mousam
       - app.drey.Dialect
       - com.artemchep.keyguard
       - io.github.kolunmi.Bazaar

# ## Flatpak Software Installation  specific for KDE desktop environment
#   - name: Install multiple Flatpak packages for KDE desktop environment
#     community.general.flatpak:
#       name:
#        - org.kde.kdenlive
#        - org.kde.krita
#        - org.kde.digikam
#        - org.kde.kcolorchooser
#        - org.kde.inkscape
#        - org.kde.kate
#     when: gnome_check.stat.exists


## Flatpak Software Installation  specific for Gnome desktop environment
  - name: Install multiple Flatpak packages for Gnome desktop environment
    community.general.flatpak:
      name:
       - com.mattjakeman.ExtensionManager
       - io.missioncenter.MissionCenter
       - be.alexandervanhee.gradia
    when: kde_check.stat.exists