
# Flatpak Software Installation 
  - name: Install multiple Flatpak packages
    community.general.flatpak:
      name:
       - app.drey.EarTag
       - app.zen_browser.zen
       - be.alexandervanhee.gradia
       - com.beavernotes.beavernotes
       - com.belmoussaoui.Obfuscate
       - com.bitwarden.desktop
       - com.emqx.MQTTX
       - com.felipekinoshita.Wildcard
       - com.github.ADBeveridge.Raider
       - com.github.unrud.VideoDownloader
       - com.jgraph.drawio.desktop
       - com.mattjakeman.ExtensionManager
       - com.rtosta.zapzap
       - com.spotify.Client
       - com.surfshark.Surfshark
       - dev.bragefuglseth.Fretboard 
       - dev.fredol.open-tv
       - io.github.Omniaevo.mqtt5-explorer
       - io.github.alainm23.planify
       - io.github.flattool.Warehouse
       - io.github.giantpinkrobots.varia
       - io.github.janbar.noson
       - io.github.qwersyk.Newelle
       - io.github.wartybix.Constrict
       - io.gitlab.adhami3310.Converter
       - io.gitlab.adhami3310.Impression
       - io.gitlab.librewolf-community
       - io.gpt4all.gpt4all.Locale
       - io.missioncenter.MissionCenter
       - md.obsidian.Obsidian 
       - net.code_industry.MasterPDFEditor 
       - org.angryip.ipscan
