  - name: Install Software for KDE Desktop
    dnf:
          name: "{{ item }}"
          state: present
    ignore_errors: yes
    loop:
          - ktorrent
          - skanlite
          - kfind
          - krita
          - digikam
          - kcolorchooser
          - inkscape
          - kate
          



        
